Removed storing password
skwashd/github_api pull request #6
Opened 2016-12-20 20:25 UTC by kmoll

2016-12-22 13:24 UTC, skwashd requested changes
@kmoll overall this is looking good. Please remove the commented line and squash this into a single commit and then I think it is ready go.

2016-12-22 13:24 UTC, skwashd commented on github_api.module
> +    // $token = $config->get('github_api_token');.
If this isn't needed it should be removed.

2017-02-21 14:29 UTC, kmoll commented
@skwashd I updated this, we needed the line, so I kept it and removed the comments.

2017-02-21 15:48 UTC, skwashd approved these changes
Looks good to me. Thanks for submitted the patch @kmoll.

2017-02-21 15:49 UTC, merged